//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmaFFFFF.CadastrBenin.DAL
{
	using System;
	using System.Collections.ObjectModel;
	using PropertyChanged;
	
	[ImplementPropertyChanged]
	public partial class CadastraleDivision
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public CadastraleDivision()
		{
			this.JuridiqueObjets = new ObservableCollection<JuridiqueObjet>();
		}
	
		public string Numero { get; set; }
		public string Nom { get; set; }
		public byte Id { get; set; }
		public Nullable<short> Niveau { get; set; }
		public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
	
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ObservableCollection<JuridiqueObjet> JuridiqueObjets { get; set; }
	}
}
