//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmaFFFFF.CadastrBenin.DAL
{
	using System;
	using System.Collections.ObjectModel;
	using PropertyChanged;
	
	[ImplementPropertyChanged]
	public partial class CadastraleSecteurs_v
	{
		public string Numero { get; set; }
		public Nullable<byte> Id { get; set; }
		public string Nom { get; set; }
		public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
	}
}
