//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmaFFFFF.CadastrBenin.DAL
{
	using System;
	using System.Collections.ObjectModel;
	using PropertyChanged;
	
	[ImplementPropertyChanged]
	public partial class CertificationDocument
	{
		public int Id { get; set; }
		public System.Guid ParcelleGUID { get; set; }
		public string CertificationDocumentTypeNom { get; set; }
		public System.DateTime Date { get; set; }
		public string Num { get; set; }
	
		public virtual CertificationDocumentType CertificationDocumentType { get; set; }
		public virtual Parcelle Parcelle { get; set; }
	}
}
