//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmaFFFFF.CadastrBenin.DAL
{
	using System;
	using System.Collections.ObjectModel;
	using PropertyChanged;
	
	[ImplementPropertyChanged]
	public partial class JuridiqueSituations_v
	{
		public string NUP { get; set; }
		public string JuridiqueTypeNom { get; set; }
		public System.Guid ProprietarePresume { get; set; }
		public string Nom { get; set; }
		public string Observations { get; set; }
	}
}
