//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmaFFFFF.CadastrBenin.DAL
{
	using System;
	using System.Collections.ObjectModel;
	using PropertyChanged;
	
	[ImplementPropertyChanged]
	public abstract partial class JuridiqueObjet
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public JuridiqueObjet()
		{
			this.TransactionObjets = new ObservableCollection<TransactionObjet>();
			this.Utilisations = new ObservableCollection<Utilisation>();
		}
	
		public System.Guid GUID { get; set; }
		public string CadSecteurNumero { get; set; }
		public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
		public Nullable<int> Superficie { get; private set; }
	
		public virtual CadastraleDivision CadastraleDivision { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ObservableCollection<TransactionObjet> TransactionObjets { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ObservableCollection<Utilisation> Utilisations { get; set; }
	}
}
