//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmaFFFFF.CadastrBenin.DAL
{
	using System;
	using System.Collections.ObjectModel;
	using PropertyChanged;
	
	[ImplementPropertyChanged]
	public partial class Parcel_ImmeubleIntersect
	{
		public long Id { get; set; }
		public string ParcelNUP { get; set; }
		public string ImmeubleNUP { get; set; }
		public System.Data.Entity.Spatial.DbGeometry ParcelShape { get; set; }
		public System.Data.Entity.Spatial.DbGeometry ImmeubleShape { get; set; }
	}
}
