//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmaFFFFF.CadastrBenin.DAL
{
	using System;
	using System.Collections.ObjectModel;
	using PropertyChanged;
	
	[ImplementPropertyChanged]
	public partial class Personne : Sujet
	{
		public string Nom { get; set; }
		public string Prenoms { get; set; }
		public Nullable<bool> Sexe { get; set; }
		public string NaissanceLieu { get; set; }
		public Nullable<System.DateTime> NaissanceDate { get; set; }
		public string Profession { get; set; }
		public string NomEtPrenome { get; set; }
	}
}
