//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmaFFFFF.CadastrBenin.DAL
{
	using System;
	using System.Collections.ObjectModel;
	using PropertyChanged;
	
	[ImplementPropertyChanged]
	public abstract partial class Sujet
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Sujet()
		{
			this.ProprietaireAnciens = new ObservableCollection<ProprietaireAncien>();
			this.ProprietairePresumes = new ObservableCollection<ProprietairePresume>();
			this.SujetDocuments = new ObservableCollection<SujetDocument>();
		}
	
		public System.Guid GUID { get; set; }
		public string Nationalite { get; set; }
		public string Telephone { get; set; }
		public string Adresse { get; set; }
		public string BP { get; set; }
		public string Email { get; set; }
	
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ObservableCollection<ProprietaireAncien> ProprietaireAnciens { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ObservableCollection<ProprietairePresume> ProprietairePresumes { get; set; }
		public virtual Etat Etat { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ObservableCollection<SujetDocument> SujetDocuments { get; set; }
	}
}
