//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmaFFFFF.CadastrBenin.DAL
{
	using System;
	using System.Collections.ObjectModel;
	using PropertyChanged;
	
	[ImplementPropertyChanged]
	public partial class Transaction
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Transaction()
		{
			this.ProprietaireAnciens = new ObservableCollection<ProprietaireAncien>();
			this.ProprietairePresumes = new ObservableCollection<ProprietairePresume>();
			this.TransactionObjets = new ObservableCollection<TransactionObjet>();
			this.Transactions1 = new ObservableCollection<Transaction>();
		}
	
		public System.Guid GUID { get; set; }
		public Nullable<System.Guid> MereTransactionGUID { get; set; }
		public string TransactionTypeNom { get; set; }
		public int TransactionDocumentId { get; set; }
		public System.DateTime DebutDate { get; set; }
		public Nullable<System.DateTime> FinDate { get; set; }
		public string Observations { get; set; }
	
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ObservableCollection<ProprietaireAncien> ProprietaireAnciens { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ObservableCollection<ProprietairePresume> ProprietairePresumes { get; set; }
		public virtual TransactionDocument TransactionDocument { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ObservableCollection<TransactionObjet> TransactionObjets { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ObservableCollection<Transaction> Transactions1 { get; set; }
		public virtual Transaction Transaction1 { get; set; }
		public virtual TransactionType TransactionType { get; set; }
	}
}
