//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gmaFFFFF.CadastrBenin.DAL
{
	using System;
	using System.Collections.ObjectModel;
	using PropertyChanged;
	
	[ImplementPropertyChanged]
	public partial class Utilisation
	{
		public int Id { get; set; }
		public string UtilisationTypeNom { get; set; }
		public System.Guid JuridiqueObjetGUID { get; set; }
		public System.DateTime Date { get; set; }
		public string Document { get; set; }
	
		public virtual JuridiqueObjet JuridiqueObjet { get; set; }
		public virtual UtilisationType UtilisationType { get; set; }
	}
}
